name: Linter

on:
  push:
    branches: [ "main" ]
  pull_request:

permissions:
  contents: read
  checks: write

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b # v4.1.5
      - uses: actions/setup-go@cdcb36043654635271a94b9a6d1392de5bb323a7 # v5.0.1
        with:
          go-version-file: 'go.mod'
      - name: Linting
        uses: golangci/golangci-lint-action@a4f60bb28d35aeee14e6880718e0c85ff1882e64 # v6.0.1
        with:
          install-mode: goinstall
          version: dc2815312726b4f374f5c69a1c183a85990917a7 # v1.58.1
          args: --timeout=1m --allow-parallel-runners --issues-exit-code=0